# Generated by Django 5.2.7 on 2025-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_datecompleted_alter_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
